name: fello
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  calendar_date_picker2: ^0.5.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  equatable: ^2.0.3
  font_awesome_flutter: ^10.6.0
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  flutter_otp_text_field: ^1.1.1
  fluttertoast: ^8.2.4
  intl: ^0.18.1
  lottie: ^2.7.0
  permission_handler: ^11.1.0
  shared_preferences: ^2.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/carousel/
    - assets/images/product/
    - assets/json/
